# Generated by Django 2.2 on 2020-07-31 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20200731_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='pic',
            new_name='image',
        ),
    ]
